# config/config.yaml
api:
  # Default provider (openai, azure, or anthropic)
  default_provider: openai
  
  # OpenAI settings
  openai:
    model: gpt-4
    temperature: 0.7
    max_tokens: 2000
    
  # Azure OpenAI settings
  azure:
    model_deployment: your-deployment-name
    api_version: 2024-02-15-preview
    temperature: 0.7
    max_tokens: 2000
    
  # Anthropic settings
  anthropic:
    model: claude-3-opus-20240229
    temperature: 0.7
    max_tokens: 2000

data:
  max_rows: 5000
  sample_size: 5
  
system:
  debug: false
  log_level: INFO