api:
  anthropic:
    max_tokens: 2000
    model: claude-3-opus-20240229
    temperature: 0.7
  azure:
    api_version: 2024-02-15-preview
    max_tokens: 2000
    model_deployment: gpt-4o-mini
    temperature: 0.7
  default_provider: azure
  openai:
    max_tokens: 2000
    model: gpt-4
    temperature: 0.7
data:
  max_rows: 5000
  sample_size: 5
system:
  debug: false
  log_level: INFO
